#!/bin/bash
#
# Make a copy of the sh.vim syntax from the current Vim installation and
# modify its syntax identifier names. The modified syntax is used to
# highlight blocks of plain shell script within ecFlow syntax, which is
# itself simply a layer on top of the shell script syntax.
#

build_for="vim"

if [[ $# -gt 1 ]]; then
    echo "usage: $0 [vim|nvim]" >&2
    exit 1
elif [[ $# -eq 1 ]]; then
    build_for=$1
fi

if [[ $build_for != vim && $build_for != nvim ]]; then
    echo "usage: $0 [vim|nvim]" >&2
    exit 1
fi

# Get the builtin sh.vim syntax file:
if [[ $build_for == nvim ]]; then
    # Neovim
    sh_syntax_file=$( nvim --headless +'lua io.write(vim.fn.globpath(vim.o.runtimepath, "syntax/sh.vim"))' +qa )
else
    # Vim
    VIMRUNTIME=$( vim -e -T dumb --cmd 'exe "set t_cm=\<C-M>" | echo $VIMRUNTIME | quit' | tr -d '[:space:]' )
    sh_syntax_file="$VIMRUNTIME/syntax/sh.vim"
fi

if [[ ! -f $sh_syntax_file ]]; then
    echo "error: cannot locate sh.vim" >&2
    exit 1
fi

# Make a hacked copy of the sh syntax file, used to embed normal sh syntax within
# blocks of the extended sh syntax:
hack_syntax_file="./syntax/sh-hack.vim"
sed -e 's/sh\([A-Z]\)/shHack\1/g' \
    -e 's/ShFold/ShHackFold/g' \
    "$sh_syntax_file" > "$hack_syntax_file"

exit 0
